sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
matrix:
  fast_finish: true
branches:
  only:
    - master
cache:
  directories:
  - node_modules
  - packages/paeckchen-core/node_modules
  - packages/paeckchen-cli/node_modules
  - packages/gulp-paeckchen/node_modules
notifications:
  email:
    on_success: never

before_script: 'npm run bootstrap; npm run linter'
script: 'npm run coverage'
after_script: "./node_modules/.bin/lcov-result-merger 'packages/*/coverage/lcov.info' | ./node_modules/.bin/coveralls"
