environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '4'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
matrix:
  fast_finish: true
max_jobs: 6
version: '{build}'
shallow_clone: true
clone_depth: 1
skip_tags: true
branches:
  only:
    - master
build: off
before_test:
  - npm cache clean
  - npm install
test_script:
  - npm run test
deploy: off
